apiVersion: apps/v1
kind: Deployment
metadata:
  name: maginx
  namespace: kubesystem
spec:
  replicas: 1
  selector:
    matchLabels:
      name: maginx
  template:
    metadata:
      labels:
        name: maginx
    spec:
      containers:
      - name: maginx
        image: macoredroid/nginx:9.2
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
        ports:
        - containerPort: 8081
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: maginx
  labels:
    name: maginx
  namespace: kubesystem
spec:
  type: NodePort
  ports:
  - name: maginx
    port: 8081
    targetPort: 8081
    nodePort: 8081
  selector:
    name: maginx
